'use strict';

module.exports = {
  PRODUCT_INVENTORY_FILLED: 'PRODUCT_INVENTORY_FILLED',
  PRODUCT_INVENTORY_WITHDRAWN: 'PRODUCT_INVENTORY_WITHDRAWN',
  PRODUCT_INVENTORY_DEPLETED: 'PRODUCT_INVENTORY_DEPLETED',
};